version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 50
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.28
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.39
    - 15.0.0
  - dependency-name: "@types/node-fetch"
    versions:
    - 2.5.9
  - dependency-name: gulp-mocha
    versions:
    - 8.0.0
  - dependency-name: jsonld
    versions:
    - 4.0.1
    - 5.0.0
  - dependency-name: mocha
    versions:
    - 8.3.1
  - dependency-name: "@types/jsonld"
    versions:
    - 1.5.2
    - 1.5.3
    - 1.5.4
  - dependency-name: typescript
    versions:
    - 4.2.2
  - dependency-name: "@types/mocha"
    versions:
    - 8.2.1
